-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_dense_layer is
port (
    flat_to_dense_streams_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_0_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_0_read : OUT STD_LOGIC;
    flat_to_dense_streams_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_1_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_1_read : OUT STD_LOGIC;
    flat_to_dense_streams_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_2_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_2_read : OUT STD_LOGIC;
    flat_to_dense_streams_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_3_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_3_read : OUT STD_LOGIC;
    flat_to_dense_streams_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_4_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_4_read : OUT STD_LOGIC;
    flat_to_dense_streams_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_5_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_5_read : OUT STD_LOGIC;
    flat_to_dense_streams_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_6_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_6_read : OUT STD_LOGIC;
    flat_to_dense_streams_7_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    flat_to_dense_streams_7_empty_n : IN STD_LOGIC;
    flat_to_dense_streams_7_read : OUT STD_LOGIC;
    dense_to_softmax_streams_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_0_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_0_write : OUT STD_LOGIC;
    dense_to_softmax_streams_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_1_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_1_write : OUT STD_LOGIC;
    dense_to_softmax_streams_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_2_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_2_write : OUT STD_LOGIC;
    dense_to_softmax_streams_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_3_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_3_write : OUT STD_LOGIC;
    dense_to_softmax_streams_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_4_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_4_write : OUT STD_LOGIC;
    dense_to_softmax_streams_5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_5_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_5_write : OUT STD_LOGIC;
    dense_to_softmax_streams_6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_6_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_6_write : OUT STD_LOGIC;
    dense_to_softmax_streams_7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    dense_to_softmax_streams_7_full_n : IN STD_LOGIC;
    dense_to_softmax_streams_7_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of cnn_dense_layer is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal dense_U0_ap_start : STD_LOGIC;
    signal dense_U0_ap_done : STD_LOGIC;
    signal dense_U0_ap_continue : STD_LOGIC;
    signal dense_U0_ap_idle : STD_LOGIC;
    signal dense_U0_ap_ready : STD_LOGIC;
    signal dense_U0_flat_to_dense_streams_0_read : STD_LOGIC;
    signal dense_U0_dense_to_softmax_streams_0_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_U0_dense_to_softmax_streams_0_write : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal dense_1_U0_ap_start : STD_LOGIC;
    signal dense_1_U0_ap_done : STD_LOGIC;
    signal dense_1_U0_ap_continue : STD_LOGIC;
    signal dense_1_U0_ap_idle : STD_LOGIC;
    signal dense_1_U0_ap_ready : STD_LOGIC;
    signal dense_1_U0_flat_to_dense_streams_1_read : STD_LOGIC;
    signal dense_1_U0_dense_to_softmax_streams_1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_1_U0_dense_to_softmax_streams_1_write : STD_LOGIC;
    signal dense_2_U0_ap_start : STD_LOGIC;
    signal dense_2_U0_ap_done : STD_LOGIC;
    signal dense_2_U0_ap_continue : STD_LOGIC;
    signal dense_2_U0_ap_idle : STD_LOGIC;
    signal dense_2_U0_ap_ready : STD_LOGIC;
    signal dense_2_U0_flat_to_dense_streams_2_read : STD_LOGIC;
    signal dense_2_U0_dense_to_softmax_streams_2_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_2_U0_dense_to_softmax_streams_2_write : STD_LOGIC;
    signal dense_3_U0_ap_start : STD_LOGIC;
    signal dense_3_U0_ap_done : STD_LOGIC;
    signal dense_3_U0_ap_continue : STD_LOGIC;
    signal dense_3_U0_ap_idle : STD_LOGIC;
    signal dense_3_U0_ap_ready : STD_LOGIC;
    signal dense_3_U0_flat_to_dense_streams_3_read : STD_LOGIC;
    signal dense_3_U0_dense_to_softmax_streams_3_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_3_U0_dense_to_softmax_streams_3_write : STD_LOGIC;
    signal dense_4_U0_ap_start : STD_LOGIC;
    signal dense_4_U0_ap_done : STD_LOGIC;
    signal dense_4_U0_ap_continue : STD_LOGIC;
    signal dense_4_U0_ap_idle : STD_LOGIC;
    signal dense_4_U0_ap_ready : STD_LOGIC;
    signal dense_4_U0_flat_to_dense_streams_4_read : STD_LOGIC;
    signal dense_4_U0_dense_to_softmax_streams_4_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_4_U0_dense_to_softmax_streams_4_write : STD_LOGIC;
    signal dense_5_U0_ap_start : STD_LOGIC;
    signal dense_5_U0_ap_done : STD_LOGIC;
    signal dense_5_U0_ap_continue : STD_LOGIC;
    signal dense_5_U0_ap_idle : STD_LOGIC;
    signal dense_5_U0_ap_ready : STD_LOGIC;
    signal dense_5_U0_flat_to_dense_streams_5_read : STD_LOGIC;
    signal dense_5_U0_dense_to_softmax_streams_5_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_5_U0_dense_to_softmax_streams_5_write : STD_LOGIC;
    signal dense_6_U0_ap_start : STD_LOGIC;
    signal dense_6_U0_ap_done : STD_LOGIC;
    signal dense_6_U0_ap_continue : STD_LOGIC;
    signal dense_6_U0_ap_idle : STD_LOGIC;
    signal dense_6_U0_ap_ready : STD_LOGIC;
    signal dense_6_U0_flat_to_dense_streams_6_read : STD_LOGIC;
    signal dense_6_U0_dense_to_softmax_streams_6_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_6_U0_dense_to_softmax_streams_6_write : STD_LOGIC;
    signal dense_7_U0_ap_start : STD_LOGIC;
    signal dense_7_U0_ap_done : STD_LOGIC;
    signal dense_7_U0_ap_continue : STD_LOGIC;
    signal dense_7_U0_ap_idle : STD_LOGIC;
    signal dense_7_U0_ap_ready : STD_LOGIC;
    signal dense_7_U0_flat_to_dense_streams_7_read : STD_LOGIC;
    signal dense_7_U0_dense_to_softmax_streams_7_din : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_7_U0_dense_to_softmax_streams_7_write : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_dense_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_1_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_1_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_2_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_2_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_3_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_3_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_4_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_4_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_5_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_5_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_6_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_6_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_dense_7_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_dense_7_U0_ap_ready : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_dense IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_0_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_0_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_0_read : OUT STD_LOGIC;
        dense_to_softmax_streams_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_0_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_0_write : OUT STD_LOGIC );
    end component;


    component cnn_dense_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_1_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_1_read : OUT STD_LOGIC;
        dense_to_softmax_streams_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_1_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_1_write : OUT STD_LOGIC );
    end component;


    component cnn_dense_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_2_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_2_read : OUT STD_LOGIC;
        dense_to_softmax_streams_2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_2_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_2_write : OUT STD_LOGIC );
    end component;


    component cnn_dense_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_3_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_3_read : OUT STD_LOGIC;
        dense_to_softmax_streams_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_3_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_3_write : OUT STD_LOGIC );
    end component;


    component cnn_dense_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_4_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_4_read : OUT STD_LOGIC;
        dense_to_softmax_streams_4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_4_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_4_write : OUT STD_LOGIC );
    end component;


    component cnn_dense_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_5_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_5_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_5_read : OUT STD_LOGIC;
        dense_to_softmax_streams_5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_5_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_5_write : OUT STD_LOGIC );
    end component;


    component cnn_dense_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_6_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_6_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_6_read : OUT STD_LOGIC;
        dense_to_softmax_streams_6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_6_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_6_write : OUT STD_LOGIC );
    end component;


    component cnn_dense_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        flat_to_dense_streams_7_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        flat_to_dense_streams_7_empty_n : IN STD_LOGIC;
        flat_to_dense_streams_7_read : OUT STD_LOGIC;
        dense_to_softmax_streams_7_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        dense_to_softmax_streams_7_full_n : IN STD_LOGIC;
        dense_to_softmax_streams_7_write : OUT STD_LOGIC );
    end component;



begin
    dense_U0 : component cnn_dense
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_U0_ap_start,
        ap_done => dense_U0_ap_done,
        ap_continue => dense_U0_ap_continue,
        ap_idle => dense_U0_ap_idle,
        ap_ready => dense_U0_ap_ready,
        flat_to_dense_streams_0_dout => flat_to_dense_streams_0_dout,
        flat_to_dense_streams_0_empty_n => flat_to_dense_streams_0_empty_n,
        flat_to_dense_streams_0_read => dense_U0_flat_to_dense_streams_0_read,
        dense_to_softmax_streams_0_din => dense_U0_dense_to_softmax_streams_0_din,
        dense_to_softmax_streams_0_full_n => dense_to_softmax_streams_0_full_n,
        dense_to_softmax_streams_0_write => dense_U0_dense_to_softmax_streams_0_write);

    dense_1_U0 : component cnn_dense_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_1_U0_ap_start,
        ap_done => dense_1_U0_ap_done,
        ap_continue => dense_1_U0_ap_continue,
        ap_idle => dense_1_U0_ap_idle,
        ap_ready => dense_1_U0_ap_ready,
        flat_to_dense_streams_1_dout => flat_to_dense_streams_1_dout,
        flat_to_dense_streams_1_empty_n => flat_to_dense_streams_1_empty_n,
        flat_to_dense_streams_1_read => dense_1_U0_flat_to_dense_streams_1_read,
        dense_to_softmax_streams_1_din => dense_1_U0_dense_to_softmax_streams_1_din,
        dense_to_softmax_streams_1_full_n => dense_to_softmax_streams_1_full_n,
        dense_to_softmax_streams_1_write => dense_1_U0_dense_to_softmax_streams_1_write);

    dense_2_U0 : component cnn_dense_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_2_U0_ap_start,
        ap_done => dense_2_U0_ap_done,
        ap_continue => dense_2_U0_ap_continue,
        ap_idle => dense_2_U0_ap_idle,
        ap_ready => dense_2_U0_ap_ready,
        flat_to_dense_streams_2_dout => flat_to_dense_streams_2_dout,
        flat_to_dense_streams_2_empty_n => flat_to_dense_streams_2_empty_n,
        flat_to_dense_streams_2_read => dense_2_U0_flat_to_dense_streams_2_read,
        dense_to_softmax_streams_2_din => dense_2_U0_dense_to_softmax_streams_2_din,
        dense_to_softmax_streams_2_full_n => dense_to_softmax_streams_2_full_n,
        dense_to_softmax_streams_2_write => dense_2_U0_dense_to_softmax_streams_2_write);

    dense_3_U0 : component cnn_dense_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_3_U0_ap_start,
        ap_done => dense_3_U0_ap_done,
        ap_continue => dense_3_U0_ap_continue,
        ap_idle => dense_3_U0_ap_idle,
        ap_ready => dense_3_U0_ap_ready,
        flat_to_dense_streams_3_dout => flat_to_dense_streams_3_dout,
        flat_to_dense_streams_3_empty_n => flat_to_dense_streams_3_empty_n,
        flat_to_dense_streams_3_read => dense_3_U0_flat_to_dense_streams_3_read,
        dense_to_softmax_streams_3_din => dense_3_U0_dense_to_softmax_streams_3_din,
        dense_to_softmax_streams_3_full_n => dense_to_softmax_streams_3_full_n,
        dense_to_softmax_streams_3_write => dense_3_U0_dense_to_softmax_streams_3_write);

    dense_4_U0 : component cnn_dense_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_4_U0_ap_start,
        ap_done => dense_4_U0_ap_done,
        ap_continue => dense_4_U0_ap_continue,
        ap_idle => dense_4_U0_ap_idle,
        ap_ready => dense_4_U0_ap_ready,
        flat_to_dense_streams_4_dout => flat_to_dense_streams_4_dout,
        flat_to_dense_streams_4_empty_n => flat_to_dense_streams_4_empty_n,
        flat_to_dense_streams_4_read => dense_4_U0_flat_to_dense_streams_4_read,
        dense_to_softmax_streams_4_din => dense_4_U0_dense_to_softmax_streams_4_din,
        dense_to_softmax_streams_4_full_n => dense_to_softmax_streams_4_full_n,
        dense_to_softmax_streams_4_write => dense_4_U0_dense_to_softmax_streams_4_write);

    dense_5_U0 : component cnn_dense_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_5_U0_ap_start,
        ap_done => dense_5_U0_ap_done,
        ap_continue => dense_5_U0_ap_continue,
        ap_idle => dense_5_U0_ap_idle,
        ap_ready => dense_5_U0_ap_ready,
        flat_to_dense_streams_5_dout => flat_to_dense_streams_5_dout,
        flat_to_dense_streams_5_empty_n => flat_to_dense_streams_5_empty_n,
        flat_to_dense_streams_5_read => dense_5_U0_flat_to_dense_streams_5_read,
        dense_to_softmax_streams_5_din => dense_5_U0_dense_to_softmax_streams_5_din,
        dense_to_softmax_streams_5_full_n => dense_to_softmax_streams_5_full_n,
        dense_to_softmax_streams_5_write => dense_5_U0_dense_to_softmax_streams_5_write);

    dense_6_U0 : component cnn_dense_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_6_U0_ap_start,
        ap_done => dense_6_U0_ap_done,
        ap_continue => dense_6_U0_ap_continue,
        ap_idle => dense_6_U0_ap_idle,
        ap_ready => dense_6_U0_ap_ready,
        flat_to_dense_streams_6_dout => flat_to_dense_streams_6_dout,
        flat_to_dense_streams_6_empty_n => flat_to_dense_streams_6_empty_n,
        flat_to_dense_streams_6_read => dense_6_U0_flat_to_dense_streams_6_read,
        dense_to_softmax_streams_6_din => dense_6_U0_dense_to_softmax_streams_6_din,
        dense_to_softmax_streams_6_full_n => dense_to_softmax_streams_6_full_n,
        dense_to_softmax_streams_6_write => dense_6_U0_dense_to_softmax_streams_6_write);

    dense_7_U0 : component cnn_dense_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dense_7_U0_ap_start,
        ap_done => dense_7_U0_ap_done,
        ap_continue => dense_7_U0_ap_continue,
        ap_idle => dense_7_U0_ap_idle,
        ap_ready => dense_7_U0_ap_ready,
        flat_to_dense_streams_7_dout => flat_to_dense_streams_7_dout,
        flat_to_dense_streams_7_empty_n => flat_to_dense_streams_7_empty_n,
        flat_to_dense_streams_7_read => dense_7_U0_flat_to_dense_streams_7_read,
        dense_to_softmax_streams_7_din => dense_7_U0_dense_to_softmax_streams_7_din,
        dense_to_softmax_streams_7_full_n => dense_to_softmax_streams_7_full_n,
        dense_to_softmax_streams_7_write => dense_7_U0_dense_to_softmax_streams_7_write);





    ap_sync_reg_dense_1_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_1_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_1_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_1_U0_ap_ready <= ap_sync_dense_1_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_2_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_2_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_2_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_2_U0_ap_ready <= ap_sync_dense_2_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_3_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_3_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_3_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_3_U0_ap_ready <= ap_sync_dense_3_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_4_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_4_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_4_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_4_U0_ap_ready <= ap_sync_dense_4_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_5_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_5_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_5_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_5_U0_ap_ready <= ap_sync_dense_5_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_6_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_6_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_6_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_6_U0_ap_ready <= ap_sync_dense_6_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_7_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_7_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_7_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_7_U0_ap_ready <= ap_sync_dense_7_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_dense_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_dense_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_dense_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_dense_U0_ap_ready <= ap_sync_dense_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= ap_sync_done;
    ap_idle <= (dense_U0_ap_idle and dense_7_U0_ap_idle and dense_6_U0_ap_idle and dense_5_U0_ap_idle and dense_4_U0_ap_idle and dense_3_U0_ap_idle and dense_2_U0_ap_idle and dense_1_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_continue <= (ap_sync_done and ap_continue);
    ap_sync_dense_1_U0_ap_ready <= (dense_1_U0_ap_ready or ap_sync_reg_dense_1_U0_ap_ready);
    ap_sync_dense_2_U0_ap_ready <= (dense_2_U0_ap_ready or ap_sync_reg_dense_2_U0_ap_ready);
    ap_sync_dense_3_U0_ap_ready <= (dense_3_U0_ap_ready or ap_sync_reg_dense_3_U0_ap_ready);
    ap_sync_dense_4_U0_ap_ready <= (dense_4_U0_ap_ready or ap_sync_reg_dense_4_U0_ap_ready);
    ap_sync_dense_5_U0_ap_ready <= (dense_5_U0_ap_ready or ap_sync_reg_dense_5_U0_ap_ready);
    ap_sync_dense_6_U0_ap_ready <= (dense_6_U0_ap_ready or ap_sync_reg_dense_6_U0_ap_ready);
    ap_sync_dense_7_U0_ap_ready <= (dense_7_U0_ap_ready or ap_sync_reg_dense_7_U0_ap_ready);
    ap_sync_dense_U0_ap_ready <= (dense_U0_ap_ready or ap_sync_reg_dense_U0_ap_ready);
    ap_sync_done <= (dense_U0_ap_done and dense_7_U0_ap_done and dense_6_U0_ap_done and dense_5_U0_ap_done and dense_4_U0_ap_done and dense_3_U0_ap_done and dense_2_U0_ap_done and dense_1_U0_ap_done);
    ap_sync_ready <= (ap_sync_dense_U0_ap_ready and ap_sync_dense_7_U0_ap_ready and ap_sync_dense_6_U0_ap_ready and ap_sync_dense_5_U0_ap_ready and ap_sync_dense_4_U0_ap_ready and ap_sync_dense_3_U0_ap_ready and ap_sync_dense_2_U0_ap_ready and ap_sync_dense_1_U0_ap_ready);
    dense_1_U0_ap_continue <= ap_sync_continue;
    dense_1_U0_ap_start <= ((ap_sync_reg_dense_1_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_2_U0_ap_continue <= ap_sync_continue;
    dense_2_U0_ap_start <= ((ap_sync_reg_dense_2_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_3_U0_ap_continue <= ap_sync_continue;
    dense_3_U0_ap_start <= ((ap_sync_reg_dense_3_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_4_U0_ap_continue <= ap_sync_continue;
    dense_4_U0_ap_start <= ((ap_sync_reg_dense_4_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_5_U0_ap_continue <= ap_sync_continue;
    dense_5_U0_ap_start <= ((ap_sync_reg_dense_5_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_6_U0_ap_continue <= ap_sync_continue;
    dense_6_U0_ap_start <= ((ap_sync_reg_dense_6_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_7_U0_ap_continue <= ap_sync_continue;
    dense_7_U0_ap_start <= ((ap_sync_reg_dense_7_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_U0_ap_continue <= ap_sync_continue;
    dense_U0_ap_start <= ((ap_sync_reg_dense_U0_ap_ready xor ap_const_logic_1) and ap_start);
    dense_to_softmax_streams_0_din <= dense_U0_dense_to_softmax_streams_0_din;
    dense_to_softmax_streams_0_write <= dense_U0_dense_to_softmax_streams_0_write;
    dense_to_softmax_streams_1_din <= dense_1_U0_dense_to_softmax_streams_1_din;
    dense_to_softmax_streams_1_write <= dense_1_U0_dense_to_softmax_streams_1_write;
    dense_to_softmax_streams_2_din <= dense_2_U0_dense_to_softmax_streams_2_din;
    dense_to_softmax_streams_2_write <= dense_2_U0_dense_to_softmax_streams_2_write;
    dense_to_softmax_streams_3_din <= dense_3_U0_dense_to_softmax_streams_3_din;
    dense_to_softmax_streams_3_write <= dense_3_U0_dense_to_softmax_streams_3_write;
    dense_to_softmax_streams_4_din <= dense_4_U0_dense_to_softmax_streams_4_din;
    dense_to_softmax_streams_4_write <= dense_4_U0_dense_to_softmax_streams_4_write;
    dense_to_softmax_streams_5_din <= dense_5_U0_dense_to_softmax_streams_5_din;
    dense_to_softmax_streams_5_write <= dense_5_U0_dense_to_softmax_streams_5_write;
    dense_to_softmax_streams_6_din <= dense_6_U0_dense_to_softmax_streams_6_din;
    dense_to_softmax_streams_6_write <= dense_6_U0_dense_to_softmax_streams_6_write;
    dense_to_softmax_streams_7_din <= dense_7_U0_dense_to_softmax_streams_7_din;
    dense_to_softmax_streams_7_write <= dense_7_U0_dense_to_softmax_streams_7_write;
    flat_to_dense_streams_0_read <= dense_U0_flat_to_dense_streams_0_read;
    flat_to_dense_streams_1_read <= dense_1_U0_flat_to_dense_streams_1_read;
    flat_to_dense_streams_2_read <= dense_2_U0_flat_to_dense_streams_2_read;
    flat_to_dense_streams_3_read <= dense_3_U0_flat_to_dense_streams_3_read;
    flat_to_dense_streams_4_read <= dense_4_U0_flat_to_dense_streams_4_read;
    flat_to_dense_streams_5_read <= dense_5_U0_flat_to_dense_streams_5_read;
    flat_to_dense_streams_6_read <= dense_6_U0_flat_to_dense_streams_6_read;
    flat_to_dense_streams_7_read <= dense_7_U0_flat_to_dense_streams_7_read;
end behav;
